import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Dumbbell, HeartPulse, MoveUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SiteLayout, useSite } from '@/components/site';
import gym from '@/assets/article-gym.jpg';
import prep from '@/assets/article-prep.jpg';
import strength from '@/assets/article-strength.jpg';
export const Route = createFileRoute('/catalog')({ head: () => ({ meta: [{ title: 'Каталог программ тренировок — Forma' }, { name: 'description', content: 'Выбирайте программы тренировок и фитнеса под свою цель, уровень и темп. Каталог Forma скоро откроется.' }, { property: 'og:title', content: 'Каталог программ тренировок — Forma' }, { property: 'og:description', content: 'Найдите подходящую программу для силы, фитнеса и здорового движения.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Catalog });
function Catalog() { const {setAudience} = useSite(); return <SiteLayout><main><section className="container-site section-space"><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-primary">КАТАЛОГ FORMA</p><div className="grid items-end gap-8 md:grid-cols-2"><h1 className="font-display text-5xl font-extrabold leading-tight md:text-7xl">Найдите свой<br /><span className="text-primary">способ двигаться.</span></h1><p className="max-w-md text-lg leading-relaxed text-muted-foreground">Программы и тренеры для разных целей и разного уровня. Каталог скоро появится — оставьте контакт, и мы расскажем о старте.</p></div></section><section className="bg-secondary/50 py-16"><div className="container-site"><h2 className="font-display text-3xl font-extrabold">Что вам ближе?</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[{title:'Начать с нуля',image:gym,icon:HeartPulse,alt:'Спортсменка готовится к тренировке'},{title:'Стать сильнее',image:strength,icon:Dumbbell,alt:'Силовая спортсменка в зале'},{title:'Двигаться увереннее',image:prep,icon:MoveUpRight,alt:'Спортсмен выполняет разминку'}].map(item => <div key={item.title} className="bg-background"><img src={item.image} alt={item.alt} width={800} height={1008} loading="lazy" className="aspect-[4/3] w-full object-cover" /><div className="flex items-center gap-3 p-5"><item.icon className="size-5 text-primary" /><h3 className="font-display text-lg font-bold">{item.title}</h3></div></div>)}</div><p className="mt-8 text-sm text-muted-foreground">Пока мы готовим каталог, реальные программы ещё не представлены.</p></div></section><section className="container-site section-space flex flex-wrap items-center justify-between gap-8"><div><h2 className="font-display text-4xl font-extrabold">Узнайте о запуске первыми.</h2><p className="mt-4 text-muted-foreground">Оставьте заявку — сообщим, когда можно будет выбрать программу.</p></div><Button asChild size="lg" className="h-12 rounded-sm"><Link to="/" hash="join" onClick={() => setAudience('client')}>Я ищу тренера <ArrowRight /></Link></Button></section></main></SiteLayout>; }
